### ISSUE TITLE
Encapsulate Hash of Child Zone Name

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/draft-thomassen-dnsop-dnssec-bootstrapping#2]
The hashing method for the Child zone name is currently referred to as "as outlined above", or similar. Define the method separately and refer to it by name.

**Comment by peterthomassen** [comment]
Now [says](https://github.com/desec-io/draft-thomassen-dnsop-dnssec-bootstrapping/blob/b2d94f555b6946f0b350e70de0d179e3a3f0cfe3/draft-thomassen-dnsop-dnssec-bootstrapping.md#signaling-intent-to-act-as-the-childs-signer) "as defined in Section 2.2" (after rendering the reference).
