### ISSUE TITLE
Extend Algorithm to Ensure Continuity

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/draft-thomassen-dnsop-dnssec-bootstrapping#3]
Extend the checks of the retrieval algorithm used by the Parental Agent (currently Sec. 2.3.2) to only deploy `DS` records when this does not break things.

**Comment by peterthomassen** [comment]
Now [says](https://github.com/desec-io/draft-thomassen-dnsop-dnssec-bootstrapping/blob/b2d94f555b6946f0b350e70de0d179e3a3f0cfe3/draft-thomassen-dnsop-dnssec-bootstrapping.md#steps-taken-by-the-parental-agent):
> The Parental Agent then MUST verify that for each signature algorithm present, (at least) one of the keys referenced in the tentative DS record set signs the Child's DNSKEY record set. [ TODO Which other checks are needed to not break anything? ]
