### ISSUE TITLE
Point out that in-bailiwick domains are not supported

### ISSUE THREAD

**Issue by peterthomassen** [desec-io/draft-thomassen-dnsop-dnssec-bootstrapping#6]
> - Should it be explicitly noted that in-bailiwick domains are not
>    supported?

https://mailarchive.ietf.org/arch/msg/dnsop/9KHWWBmWyJyy7OxNAl5qshqBJAs/

I wonder where this belongs -- Security Considerations? Operational Recommendations? Protocol Definition? ... @letoams

**Comment by letoams** [comment]
On Mon, 8 Nov 2021, Peter Thomassen wrote:

>        o  Should it be explicitly noted that in-bailiwick domains are not
>           supported?
> 
> https://mailarchive.ietf.org/arch/msg/dnsop/9KHWWBmWyJyy7OxNAl5qshqBJAs/
> 
> I wonder where this belongs -- Security Considerations? Operational Recommendations? Protocol Definition? ...
> @letoams

Maybe in Introduction and possibly Abstract ?

Paul
